### PR TITLE
Update scala-compiler, scala-library to 2.13.10 to fix CVE

### PR DESCRIPTION
**Pull request by rhuddleston**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @rhuddleston,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by rhuddleston** [comment]
I already signed that agreement (twice) so not sure why it still says not complete

**Review by eed3si9n — APPROVED** [review]
Thanks @rhuddleston!

**Comment by rhuddleston** [comment]
okay signed CLA a 3rd time and looks like we're good now

**Pull request merged**
