### PR TITLE
Drop CompilerCache

### LINKED ISSUE #835: Really remove resident compiler (CompilerCache)
Ref https://github.com/sbt/sbt/issues/1287
Ref https://github.com/sbt/zinc/issues/340

Maybe this is a good opportunity to remove `CompilerCache` in general.

It was turned off by default 

```scala
compilerCache <<= state map { _ get Keys.stateCompilerCache getOrElse compiler.CompilerCache.fresh },
```

in https://github.com/sbt/sbt/commit/6769c942083d37c7729adcd26f43d441ab89ecf1 when it was first introduced in 2012 . There was an attempt to remove it in 2017 https://github.com/sbt/zinc/pull/345, but it didn't go all the way. So retronym added a TODO to remove it in 2019 when the compiler became `java.io.Closable` in https://github.com/scala/scala/pull/7366 - https://github.com/sbt/zinc/pull/643.

_Originally posted by @eed3si9n in https://github.com/sbt/zinc/pull/829#issuecomment-658245805_

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #835

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/840/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by dwijnand** [comment]
I'm happy to rebase #839 on top of this, so we can review what's left over.  Does that work for you?

**Comment by eed3si9n** [comment]
Sounds good.

**Comment by dwijnand** [comment]
Happy to merge this?

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
