### PR TITLE
Add files from which sbt adds newlines at EOF

### PR DESCRIPTION
**Pull request by jvican**
I don't know if this is a bug or not, but it's annoying me, and someone
has to do it! ^^

See https://github.com/sbt/zinc/issues/344.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/352/head&deploy_to_bintray=false">this link.</A>

**Review by dwijnand — APPROVED** [review]
LGTM. It's adding newlines at EOF, btw.

**Comment by jvican** [comment]
Right, it's adding them instead of removing them. Do you know why? In theory, sbt should not be doing this kind of changes to the sources of a project. Or is it maybe the formatter?
  
In any case, this is not an important discussion...

**Review by Duhemm — APPROVED** [review]
LGTM

**Review by eed3si9n — APPROVED** [review]
These are resource files for testing right?
If so we can merge this without ripple PRs pending drone passage.

**Comment by jvican** [comment]
> These are resource files for testing right?
If so we can merge this without ripple PRs pending drone passage.
  
Yeah, this can be merged right away. Waiting for CI...

**Pull request merged**
