### PR TITLE
Pimp occurrences replaced with Enrich

### LINKED ISSUE #309: Rename any use of the term "Pimp" to "Enrich"
There's been a number of discussion on Twitter about how horrible the choice of term "Pimp" was to the impression of Scala:

- https://twitter.com/coda/status/93003343965851648
- https://twitter.com/coda/status/93049114106920961

> Refactored: plz don't use the "pimp" metaphor; it has unintended connotations which have offended and alienated potential Scala programmers.

The standard replacement is "Enrich", "Enrichment", or "RichX".
I sometimes call them "method injection" or "static monkey patching", but never pimp.

### PR DESCRIPTION
**Pull request by ubaldop**
Hi there, this PR renames all the `Pimp` occurrences with `Enrich` (i.e.: it fixes #309).
Hope it is enough!

Cheers,

@P3trur0

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/326/head&deploy_to_bintray=false">THIS LINK.</A>

**Comment by eed3si9n** [comment]
Thank you very much!

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/67/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.0.x-pull/326/head-1.0-1.0-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/67/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | 1.0.x                | sbt/sbt@25d393bd8b34e3bf72d129c2427349c7aa881701
  zinc              | pull/326/head        | sbt/zinc@85716654f18ac39aa6bf5e243293623d7b9a2c15
  io                | 1.0                  | sbt/io@880de81bcc9bd4308885d2515d0a1b746026b946
  librarymanagement | 1.0                  | sbt/librarymanagement@7e87603b5fd3fa0d0ce38f6e85755d3973ddf114
  util              | 1.0                  | sbt/util@54cf4a43bb560d2e6fdc48fb51a376ca4228da03
  website           | 1.0.x                | sbt/website@5c32a0afcf64dc600ff154f5456026e2a74dc668

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=1.0.x&zinc=pull/326/head&io=1.0&librarymanagement=1.0&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/68/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.0.x-pull/326/head-1.0-1.0-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/68/">has checked</A> the following projects against Scala 2.12, 2.11, 2.10:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | 1.0.x                | sbt/sbt@25d393bd8b34e3bf72d129c2427349c7aa881701
  zinc              | pull/326/head        | sbt/zinc@85716654f18ac39aa6bf5e243293623d7b9a2c15
  io                | 1.0                  | sbt/io@880de81bcc9bd4308885d2515d0a1b746026b946
  librarymanagement | 1.0                  | sbt/librarymanagement@7e87603b5fd3fa0d0ce38f6e85755d3973ddf114
  util              | 1.0                  | sbt/util@54cf4a43bb560d2e6fdc48fb51a376ca4228da03
  website           | 1.0.x                | sbt/website@5c32a0afcf64dc600ff154f5456026e2a74dc668

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=1.0.x&zinc=pull/326/head&io=1.0&librarymanagement=1.0&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Review by eed3si9n — APPROVED** [review]
LGTM
sbt/sbt didn't contain direct reference so it should be safe to merge this.

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/69/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.0.x-pull/326/head-1.0-1.0-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/69/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | 1.0.x                | sbt/sbt@25d393bd8b34e3bf72d129c2427349c7aa881701
  zinc              | pull/326/head        | sbt/zinc@85716654f18ac39aa6bf5e243293623d7b9a2c15
  io                | 1.0                  | sbt/io@880de81bcc9bd4308885d2515d0a1b746026b946
  librarymanagement | 1.0                  | sbt/librarymanagement@7e87603b5fd3fa0d0ce38f6e85755d3973ddf114
  util              | 1.0                  | sbt/util@54cf4a43bb560d2e6fdc48fb51a376ca4228da03
  website           | 1.0.x                | sbt/website@5c32a0afcf64dc600ff154f5456026e2a74dc668

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=1.0.x&zinc=pull/326/head&io=1.0&librarymanagement=1.0&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Pull request merged**
