### PR TITLE
Upgrade to sbt 1.0.0-RC3

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Blocked on https://github.com/thesamet/sbt-protoc/issues/32. @xuwei-k has already provided the upstream fix: https://github.com/thesamet/sbt-protoc/pull/33, we just need a release.

**Comment by SethTisue** [comment]
this is currently blocking https://github.com/scala/community-builds/pull/581

**Comment by eed3si9n** [comment]
sbt-protoc 0.99.12-rc5 is available now. I locally changed it yesterday to run unidoc.

**Comment by eed3si9n** [comment]
Closing this in favor of https://github.com/sbt/zinc/pull/394

**Comment by jvican** [comment]
This is an issue. Was this close intentional? We usually close issues when PRs hit master.

**Pull request closed without merging**
