### PR TITLE
Dependency: avoid creating tuples.

### PR DESCRIPTION
**Pull request by diesalbla**
The `Dependency` file was a source of allocations of `Tuple2` objects. Given that `resolveNonLocalClass` is a completely private method (does not seem to be used anywhere else), and that the second value always flows to a local field assignment, we can do that assignment in the procedure and avoid creating the tuple.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @diesalbla,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/715/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Review by eed3si9n — APPROVED** [review]
@diesalbla Thanks! The change LGTM

**Comment by eed3si9n** [comment]
@diesalbla Let me know when you've signed CLA.

**Review by jvican — APPROVED** [review]
LGTM :+1: thanks @diesalbla

**Comment by diesalbla** [comment]
Had forgotten about this one... after a similar PR on scalac, Jason Zaugg mentioned that tuple allocations are often removed by Scala compiler itself (when enabling optimisation). Not sure if this will still be needed then.

**Comment by eed3si9n** [comment]
> Not sure if this will still be needed then.

Closing this for now.

**Pull request closed without merging**
