### PR TITLE
Get fullName post flatten, to get flatten names

### LINKED ISSUE #1233: Zinc reports incorrect class file names
## Steps

```sh
git clone git@github.com:vasilmkd/zinc-wrong-class-names.git
cd zinc-wrong-class-names
sbt "clean; show compileOutputs"
```

**Warning:** The compilation can take 35+ seconds to complete. Check the note at the end of this post.

The output should look similar to the following, modulo local machine paths. Only the names of the `.class` files are important.

```
vasil@Vasil-JetBrains zinc-wrong-class-names % sbt "clean; show compileOutputs"
[info] welcome to sbt 1.9.3 (Eclipse Adoptium Java 17.0.8)
[info] loading global plugins from /Users/vasil/.sbt/1.0/plugins
[info] loading project definition from /Users/vasil/IdeaProjects/zinc-wrong-class-names/project
[info] loading settings for project zinc-wrong-class-names from build.sbt ...
[info] set current project to zinc-wrong-class-names (in build file:/Users/vasil/IdeaProjects/zinc-wrong-class-names/)
[success] Total time: 0 s, completed Aug 7, 2023, 5:47:03 PM
[info] compiling 1 Scala source to /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes ...
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$OuterLevelWithVeryVeryVeryLongClassName11$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$OuterLevelWithVeryVeryVeryLongClassName11$OuterLevelWithVeryVeryVeryLongClassName12$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$OuterLevelWithVeryVeryVeryLongClassName11$OuterLevelWithVeryVeryVeryLongClassName12$OuterLevelWithVeryVeryVeryLongClassName13$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$OuterLevelWithVeryVeryVeryLongClassName11$OuterLevelWithVeryVeryVeryLongClassName12$OuterLevelWithVeryVeryVeryLongClassName13$OuterLevelWithVeryVeryVeryLongClassName14$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$OuterLevelWithVeryVeryVeryLongClassName11$OuterLevelWithVeryVeryVeryLongClassName12$OuterLevelWithVeryVeryVeryLongClassName13$OuterLevelWithVeryVeryVeryLongClassName14$OuterLevelWithVeryVeryVeryLongClassName15$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$OuterLevelWithVeryVeryVeryLongClassName11$OuterLevelWithVeryVeryVeryLongClassName12$OuterLevelWithVeryVeryVeryLongClassName13$OuterLevelWithVeryVeryVeryLongClassName14$OuterLevelWithVeryVeryVeryLongClassName15$OuterLevelWithVeryVeryVeryLongClassName16$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$OuterLevelWithVeryVeryVeryLongClassName11$OuterLevelWithVeryVeryVeryLongClassName12$OuterLevelWithVeryVeryVeryLongClassName13$OuterLevelWithVeryVeryVeryLongClassName14$OuterLevelWithVeryVeryVeryLongClassName15$OuterLevelWithVeryVeryVeryLongClassName16$OuterLevelWithVeryVeryVeryLongClassName17$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$OuterLevelWithVeryVeryVeryLongClassName11$OuterLevelWithVeryVeryVeryLongClassName12$OuterLevelWithVeryVeryVeryLongClassName13$OuterLevelWithVeryVeryVeryLongClassName14$OuterLevelWithVeryVeryVeryLongClassName15$OuterLevelWithVeryVeryVeryLongClassName16$OuterLevelWithVeryVeryVeryLongClassName17$OuterLevelWithVeryVeryVeryLongClassName18$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$OuterLevelWithVeryVeryVeryLongClassName11$OuterLevelWithVeryVeryVeryLongClassName12$OuterLevelWithVeryVeryVeryLongClassName13$OuterLevelWithVeryVeryVeryLongClassName14$OuterLevelWithVeryVeryVeryLongClassName15$OuterLevelWithVeryVeryVeryLongClassName16$OuterLevelWithVeryVeryVeryLongClassName17$OuterLevelWithVeryVeryVeryLongClassName18$OuterLevelWithVeryVeryVeryLongClassName19$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$OuterLevelWithVeryVeryVeryLongClassName11$OuterLevelWithVeryVeryVeryLongClassName12$OuterLevelWithVeryVeryVeryLongClassName13$OuterLevelWithVeryVeryVeryLongClassName14$OuterLevelWithVeryVeryVeryLongClassName15$OuterLevelWithVeryVeryVeryLongClassName16$OuterLevelWithVeryVeryVeryLongClassName17$OuterLevelWithVeryVeryVeryLongClassName18$OuterLevelWithVeryVeryVeryLongClassName19$OuterLevelWithVeryVeryVeryLongClassName20$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$OuterLevelWithVeryVeryVeryLongClassName11$OuterLevelWithVeryVeryVeryLongClassName12$OuterLevelWithVeryVeryVeryLongClassName13$OuterLevelWithVeryVeryVeryLongClassName14$OuterLevelWithVeryVeryVeryLongClassName15$OuterLevelWithVeryVeryVeryLongClassName16$OuterLevelWithVeryVeryVeryLongClassName17$OuterLevelWithVeryVeryVeryLongClassName18$OuterLevelWithVeryVeryVeryLongClassName19$OuterLevelWithVeryVeryVeryLongClassName20$MalformedNameExample$.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$OuterLevelWithVeryVeryVeryLongClassName11$OuterLevelWithVeryVeryVeryLongClassName12$OuterLevelWithVeryVeryVeryLongClassName13$OuterLevelWithVeryVeryVeryLongClassName14$OuterLevelWithVeryVeryVeryLongClassName15$OuterLevelWithVeryVeryVeryLongClassName16$OuterLevelWithVeryVeryVeryLongClassName17$OuterLevelWithVeryVeryVeryLongClassName18$OuterLevelWithVeryVeryVeryLongClassName19$OuterLevelWithVeryVeryVeryLongClassName20$MalformedNameExample.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/classes/OuterLevelWithVeryVeryVeryLongClassName1.class
[info] * /Users/vasil/IdeaProjects/zinc-wrong-class-names/target/scala-2.13/zinc/inc_compile_2.13.zip
[success] Total time: 35 s, completed Aug 7, 2023, 5:47:38 PM
```

## Problem

These names would never be generated by the `scalac` compiler, because they are too long for the local file systems and can cause exceptions when opened for reading in a JVM process. They exceed 255 characters in length.

```sh
cd target/scala-2.13/classes
ls
```

These are the actual `.class` files generated by `scalac`.

```
OuterLevelWithVeryVeryVeryLongClassName1$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$21cd1be25088dedb16ca1b3c346466fb$$$$eryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$21cd1be25088dedb16ca1b3c346466fb$$$$eryLongClassName7$OuterLevelWithVeryVeryVeryLongClassName8$OuterLevelWithVeryVeryVeryLongClassName9$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$361c0db7030df22c21772c193d391$$$$yLongClassName19$OuterLevelWithVeryVeryVeryLongClassName20$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$361c0db7030df22c21772c193d391$$$$yLongClassName19$OuterLevelWithVeryVeryVeryLongClassName20$MalformedNameExample$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$361c0db7030df22c21772c193d391$$$$yLongClassName19$OuterLevelWithVeryVeryVeryLongClassName20$MalformedNameExample.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$7e70169f8f612a14697f8fd52119750$$$$yLongClassName15$OuterLevelWithVeryVeryVeryLongClassName16$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$7e70169f8f612a14697f8fd52119750$$$$yLongClassName15$OuterLevelWithVeryVeryVeryLongClassName16$OuterLevelWithVeryVeryVeryLongClassName17$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$973a10bc1cd9792c988bf49bee47b56$$$$ryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$973a10bc1cd9792c988bf49bee47b56$$$$ryLongClassName9$OuterLevelWithVeryVeryVeryLongClassName10$OuterLevelWithVeryVeryVeryLongClassName11$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$9a7e92c93110f2442b3ebd9c453788$$$$yLongClassName11$OuterLevelWithVeryVeryVeryLongClassName12$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$9a7e92c93110f2442b3ebd9c453788$$$$yLongClassName11$OuterLevelWithVeryVeryVeryLongClassName12$OuterLevelWithVeryVeryVeryLongClassName13$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$9f428b41847a5866a8323f5944a36d$$$$yLongClassName13$OuterLevelWithVeryVeryVeryLongClassName14$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$9f428b41847a5866a8323f5944a36d$$$$yLongClassName13$OuterLevelWithVeryVeryVeryLongClassName14$OuterLevelWithVeryVeryVeryLongClassName15$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$d292b257125352e68f2f62fd843b554$$$$yLongClassName17$OuterLevelWithVeryVeryVeryLongClassName18$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$d292b257125352e68f2f62fd843b554$$$$yLongClassName17$OuterLevelWithVeryVeryVeryLongClassName18$OuterLevelWithVeryVeryVeryLongClassName19$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$f1136b7659b86ea0804013acf91cbef$$$$eryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVer$$$$f1136b7659b86ea0804013acf91cbef$$$$eryLongClassName5$OuterLevelWithVeryVeryVeryLongClassName6$OuterLevelWithVeryVeryVeryLongClassName7$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$.class
OuterLevelWithVeryVeryVeryLongClassName1$OuterLevelWithVeryVeryVeryLongClassName2$OuterLevelWithVeryVeryVeryLongClassName3$OuterLevelWithVeryVeryVeryLongClassName4$OuterLevelWithVeryVeryVeryLongClassName5$.class
OuterLevelWithVeryVeryVeryLongClassName1.class
```

These names come from https://github.com/scala/scala/blob/98a42345385cc8adccde36c21f3192d4b4862087/src/reflect/scala/reflect/internal/StdNames.scala#L49-L86.

## Expectation

The `compileOutputs` reported by Zinc should match the actual class files generated by `scalac`.

In IntelliJ IDEA, this problem manifests as part of our compilation pipeline which uses Zinc.
https://youtrack.jetbrains.com/issue/SCL-21477/File-name-too-long-error-when-building-projects-like-Apache-Spark

This is a pretty serious issue. I would appreciate any help in diagnosing it.

## Notes
On a side note, the compilation of the single Scala source file `main.scala` takes 35+ seconds and cannot be canceled with `ctrl+C`. This seems excessive, since most of the definitions are empty object definitions.

### PR DESCRIPTION
**Pull request by dwijnand**
The reason this doesn't affect Scala 3 is because Scala 3 calls the zinc callback to register products during it's last, JVM bytecode emitting, phase.  That affects pipelining, but I left problem for another day.  Meanwhile, I found that the name is changed, in both compilers, in the "flatten" phase, so if I phase travel to that phase, getting the name (which is a recursive emission, through the ownership chain) will do the necessary "compatify" of long names.

Initially I tried compacting the name we already had, but the names didn't line up, because it was compacting the final name, rather than one of the owner names (as well as duplicating the implementation of compatify).  That's also why I'm introducing `checkProductsExist` - to assert not only that the metadata matches the test expectations, but also the metadata matches the filesystem.

### CODE REVIEW

**Comment by lrytz** [comment]
Once this is merged it needs to be ported to https://github.com/scala/scala/blob/2.13.x/src/sbt-bridge/scala/tools/xsbt/CallbackGlobal.scala

**Comment by eed3si9n** [comment]
I am planning to release 1.9.x soon, so I'll merge this as-is.

**Review by eed3si9n — APPROVED** [review]

**Comment by SethTisue** [comment]
tracking apparent regression at https://github.com/scala/bug/issues/12868

**Comment by SethTisue** [comment]
revert PR https://github.com/sbt/zinc/pull/1256

**Pull request merged**
