### PR TITLE
Avoid null delegate reporter

### LINKED ISSUE #806: NPE under -Vdebug
I turn up compiler debug `-Vdebug -Vtyper -Vlog:typer`.

It looks like `SymbolTable` emits a line of debug output after `var delegate` is [cleared](https://github.com/sbt/zinc/blob/develop/internal/compiler-bridge/src/main/scala/xsbt/CompilerInterface.scala#L131).

It's happened on a couple of sample sbt projects. Maybe only since 2.13.2?

```
[error] java.lang.NullPointerException
[error] xsbt.DelegatingReporter.info0(DelegatingReporter.scala:181)
[error] scala.tools.nsc.reporters.MakeFilteringForwardingReporter.doReport(ForwardingReporter.scala:59)
[error] scala.tools.nsc.reporters.FilteringReporter.info0(Reporter.scala:93)
[error] scala.reflect.internal.Reporter.echo(Reporting.scala:112)
[error] scala.reflect.internal.Reporting.inform(Reporting.scala:73)
[error] scala.reflect.internal.Reporting.inform$(Reporting.scala:73)
[error] scala.reflect.internal.SymbolTable.inform(SymbolTable.scala:28)
[error] scala.reflect.internal.Reporting.inform(Reporting.scala:56)
[error] scala.reflect.internal.Reporting.inform$(Reporting.scala:56)
[error] scala.reflect.internal.SymbolTable.inform(SymbolTable.scala:28)
[error] scala.tools.nsc.Global.debuglog(Global.scala:311)
[error] scala.reflect.internal.SymbolTable$perRunCaches$.clearAll(SymbolTable.scala:450)
[error] scala.tools.nsc.Global.close(Global.scala:1735)
[error] xsbt.CachedCompiler0.close(CompilerInterface.scala:100)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:98)
```

https://github.com/scala/bug/issues/12041#issuecomment-644197129

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #806

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @som-snytt,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by som-snytt** [comment]
Just a placeholder with an old commit. Needs test, etc.

**Review by lrytz — APPROVED** [review]
LGTM

**Comment by som-snytt** [comment]
Just hit this again. Maybe someone could merge it.

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Pull request merged**
