### PR TITLE
Remove warmings, cleanup & DRY up scripted commands

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/330/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/330/head&deploy_to_bintray=false">this link.</A>

**Comment by dwijnand** [comment]
[edit: wrong PR]

**Review by eed3si9n — APPROVED** [review]

**Review by Duhemm — APPROVED** [review]

**Review by jvican — APPROVED** [review]

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/330/head&deploy_to_bintray=false">this link.</A>

**Pull request merged**
