### PR TITLE
Add passing test case for default parameters in classes

### PR DESCRIPTION
**Pull request by jvican**
This pull request adds a test case for @jrudolph's issue https://github.com/sbt/zinc/issues/594. However, it is passing, so it seems that the issue he diagnosed is not reproducible in master and may have already been fixed.
  
As I'm not sure if the minimized example provided in the ticket is for sure a good reproduction of the original issue in akka, @jrudolph would you mind publishing locally zinc from master and checking if the error persists in the akka build?

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/596/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by jrudolph** [comment]
Thanks a lot, @jvican.

> publishing locally zinc from master and checking if the error persists in the akka build?

Sure. What would be the fastest way to make sure that the local zinc version would be picked up by sbt?

**Comment by jvican** [comment]
> Sure. What would be the fastest way to make sure that the local zinc version would be picked up by sbt?
  
I think the fastest way would be to publish a local sbt version of the sbt version you use in the akka build with the aforementioned change in zinc.

**Comment by jrudolph** [comment]
Ok, I'll have a try.

**Comment by jrudolph** [comment]
I just tried your test on a few older commits of zinc and it seems 746d474 has fixed it (which was pretty likely based on its commit message).

**Review by jrudolph — APPROVED** [review]
LGTM

**Comment by jvican** [comment]
Ha, can you believe I didn't remember fixing this before? I even had a lot of tests to cover this scenario. Well, I'm happy this is now fixed. I'm closing since we're already testing this. Thank you @jrudolph for following this through and the initial bug report -- next time maybe we get to find an issue with latest master :smile:

**Comment by jrudolph** [comment]
Yep, having master already fixed it is really the second best option (after no problem at all ;) )

**Pull request closed without merging**
