### PR TITLE
FPORT: Assorted incremental compiler bug fixes

### PR DESCRIPTION
**Pull request by Duhemm**
This is the non-release notes, non-scripted tests part of forward porting https://github.com/sbt/sbt/pull/2343.

Cherry-picking this was harder than most of the others I'm doing in sbt/sbt#2352, so @adriaanm and @romanowski, as well as perhaps @gkossakowski and @Duhemm, a review here wouldn't hurt at all. Thanks, sorry for the inconvenience.

(Supersedes #48, thanks @dwijnand)

### CODE REVIEW

**Comment by dwijnand** [comment]
@Duhemm Sadly this looks like it was passing in Travis, but it's now conflicting with changes, I think from #54. I tried rebasing it locally, but it got tricky, so I'd rather leave it to your capable hands..

**Comment by Duhemm** [comment]
I just rebased it. Thanks!

**Comment by dwijnand** [comment]
The 2.10.5 build failed with "Caused by: java.util.NoSuchElementException: key not found: run
" (among possibly other failures).

I've restarted it in case it's flakiness.

**Comment by adriaanm** [comment]
retro-LGTM :-) I would love to see most of this code move to scalac in 2.11.9/2.12.0 and on! (As you know, I experimented with this here: https://github.com/adriaanm/scala/tree/sbt-api-consolidate)

**Pull request merged**
