### PR TITLE
ClassfileManagerType to ClassFileManagerType name refactoring

### PR DESCRIPTION
**Pull request by knirski**
Fix remaining naming inconsistency described in #254 .

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @sepulkarz,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by eed3si9n** [comment]
```
[error] /home/travis/build/sbt/zinc/internal/zinc-scripted/src/test/scala/sbt/internal/inc/IncHandler.scala:336: type ClassfileManagerType is not a member of package xsbti.compile
[error]       val transactional: xsbti.Maybe[xsbti.compile.ClassfileManagerType] =
[error]   
```

**Review by jvican — APPROVED** [review]
Thanks @sepulkarz! :smile:
  
The error that Eugene spotted suggests that there's a use site of `ClassfileManagerType` thas hasn't been renamed. That is probably located in the `zinc-compile` sbt subproject or something alike.
  
The overall changes look nice!

**Comment by knirski** [comment]
Thanks, I must have overlooked it somehow. Fixed now.

**Review by romanowski — APPROVED** [review]

**Comment by jvican** [comment]
CI is green, we got two signoff's, merging! Thanks again @sepulkarz.

**Pull request merged**
