### PR TITLE
Restore ClassFileManager binary compatibility

### PR DESCRIPTION
**Pull request by eatkins**
With sbt 1.4.0-M2, the swoval scala.js project cannot compile because of
the removal of the file based delete method from ClassFileManager:
```
[error] ## Exception when compiling 27 sources to
${SWOVAL_LOCATION}/nio-js/.js/target/scala-2.12/classes
[error] java.lang.NoSuchMethodError: 'void
xsbti.compile.ClassFileManager.delete(java.io.File[])'
[error]
org.scalajs.sbtplugin.SBTCompat$$anon$1.delete(SBTCompat.scala:49)
```

To get the swoval build to work, I restored but deprecated the delete
and generate methods in ClassFileManger. I also had to add default
implementations of the VirtualFile versions of these methods. The
defaults work by converting the virtual files to regular files and
invoking the legacy apis that take file arguments.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/902/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by eatkins** [comment]
Builds on top of #901 which could be dropped in favor of this.

**Comment by smarter** [comment]
> To get the swoval build to work, I restored but deprecated the delete
and generate methods in ClassFileManger.

Both sbt-dotty and sbt-scalajs (as you encountered) rely on these APIs, can they be properly reimplemented using the new VirtualFile stuff? Even better would be if zinc provided a higher-level API to just let the plugins declare the files that need to be deleted, as I pleaded for two years ago: https://github.com/sbt/zinc/issues/579

**Comment by eatkins** [comment]
> Both sbt-dotty and sbt-scalajs (as you encountered) rely on these APIs, can they be properly reimplemented using the new VirtualFile stuff? Even better would be if zinc provided a higher-level API to just let the plugins declare the files that need to be deleted, as I pleaded for two years ago: #579

That would be great but it is beyond the scope of this PR. I simply want users (including myself) to be able to upgrade sbt versions without having to upgrade their sbt plugin versions.

**Comment by smarter** [comment]
Right, I'll leave a comment in the original issue.

**Comment by eed3si9n** [comment]
I thought I added https://github.com/sbt/zinc/pull/765 for Scala.JS. Did it not work?

**Comment by eatkins** [comment]
It did not.

**Comment by eatkins** [comment]
I use a pretty old version of scala.js in swoval: 0.6.26. I'm also using sbt-scalajs-crossproject 0.4.0.

**Comment by eatkins** [comment]
I double checked with the latest sbt and zinc code in https://github.com/swoval/swoval cannot compile the scala.js project without this patch.

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
