### PR TITLE
Fix #312: Improve `ExternalHooks` API

### LINKED ISSUE #312: Better API for custom ClassfileManager
sbt 0.13:
```scala
  def dottyPatchIncOptions(incOptions: IncOptions): IncOptions = {
    val inheritedNewClassfileManager = incOptions.newClassfileManager
    val newClassfileManager = () => new ClassfileManager {
      private[this] val inherited = inheritedNewClassfileManager()

      def delete(classes: Iterable[File]): Unit = {
        val tastySuffixes = List(".tasty", ".hasTasty")
        inherited.delete(classes flatMap { classFile =>
          val dottyFiles = if (classFile.getPath endsWith ".class") {
            val prefix = classFile.getAbsolutePath.stripSuffix(".class")
            tastySuffixes.map(suffix => new File(prefix + suffix)).filter(_.exists)
          } else Nil
          classFile :: dottyFiles
        })
      }

      def generated(classes: Iterable[File]): Unit = inherited.generated(classes)
      def complete(success: Boolean): Unit = inherited.complete(success)
    }
    incOptions.withNewClassfileManager(newClassfileManager)
  }
```

sbt 1.0:
```scala
  // Copy-pasted from sbt where it's private
  private case class WrappedClassFileManager(internal: ClassFileManager,
                                             external: Option[ClassFileManager])
      extends ClassFileManager {

    override def delete(classes: Array[File]): Unit = {
      external.foreach(_.delete(classes))
      internal.delete(classes)
    }

    override def complete(success: Boolean): Unit = {
      external.foreach(_.complete(success))
      internal.complete(success)
    }

    override def generated(classes: Array[File]): Unit = {
      external.foreach(_.generated(classes))
      internal.generated(classes)
    }
  }

  def dottyPatchIncOptions(incOptions: IncOptions): IncOptions = {
    val inheritedNewClassFileManager = ClassFileManagerUtil.getDefaultClassFileManager(incOptions)
    val tastyFileManager = new ClassFileManager {
      private[this] val inherited = inheritedNewClassFileManager

      def delete(classes: Array[File]): Unit = {
        val tastySuffixes = List(".tasty", ".hasTasty")
        inherited.delete(classes flatMap { classFile =>
          if (classFile.getPath endsWith ".class") {
            val prefix = classFile.getAbsolutePath.stripSuffix(".class")
            tastySuffixes.map(suffix => new File(prefix + suffix)).filter(_.exists)
          } else Nil
        })
      }

      def generated(classes: Array[File]): Unit = {}
      def complete(success: Boolean): Unit = {}
    }
    val inheritedHooks = incOptions.externalHooks
    val hooks = new ExternalHooks {
      override def externalClassFileManager() = Option(inheritedHooks.externalClassFileManager.orElse(null)) match {
        case Some(prevManager) =>
          Optional.of(WrappedClassFileManager(prevManager, Some(tastyFileManager)))
        case None =>
          Optional.of(tastyFileManager)
      }
      override def externalLookup() = inheritedHooks.externalLookup()
    }
    incOptions.withExternalHooks(hooks)
  }
```

I assume that for sbt 2.0 we will need 1000 lines of code to do this :).

### PR DESCRIPTION
**Pull request by jvican**
See ticket for details and discussion.
  
/cc @smarter @sjrd

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/363/head&deploy_to_bintray=false">this link.</A>

**Comment by jvican** [comment]
@eed3si9n Can you take care of creating a ripple PR for this? I have no time to do it. Should be really simple.

**Comment by sjrd** [comment]
Definitely an improvement over the current master. It looks like it would do the right thing with the code at https://github.com/sbt/zinc/issues/312#issuecomment-315521237, AFAICT by reading the code from the PR and from the existing code in `ClassfileManager`. I don't have time this week-end to actually test it.

**Review by romanowski — APPROVED** [review]
Nice work. TBH we (with @pkukielka) didn't thing about verbosity - we just want to plug Intelij integration in.

**Comment by jvican** [comment]
Yeah, it's understandable. Thanks for chiming in @romanowski :smile:.

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
