### PR TITLE
Some warnings cleanup

### PR DESCRIPTION
**Pull request by lukaszwawrzyk**
https://github.com/sbt/zinc/issues/349
I got rid of all warnings I knew how. 
There are warnings related to compatibility between scala versions and multiple warnings about unused method parameters, but I am not sure if it is safe to touch them.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.x&zinc=pull/549/head&io=1.x&librarymanagement=1.x&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/787/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.x-pull/549/head-1.x-1.x-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/787/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@1d7b35bd67722511b9a058113e7a1070984e6758
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/549">pull/549/head       </A> | sbt/zinc@c10957be4cfd228df1d9c1df68b44cd243b3d603
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@0e4ee5a2ae958c26cef2ed5e61431708c09959b1
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.x">1.x                 </A> | sbt/librarymanagement@6e4ad6ebd4042d3b9f1631b4a7a20d27aaa87db8
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@b412c9c92991e27f48ad90153e74a10198246551
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | 

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=pull/549/head&io=1.x&librarymanagement=1.x&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by eed3si9n — APPROVED** [review]
LGTM

**Review by jvican — APPROVED** [review]

**Pull request merged**
