### PR TITLE
Fix undercompilation matching a parent sealed

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/979/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Review by eed3si9n — APPROVED** [review]
thanks @dwijnand

**Review by retronym — APPROVED** [review]
Might need a forward port to Scala3, IIRC it has a new implementation of API hashing

**Comment by bishabosha** [comment]
> Might need a forward port to Scala3, IIRC it has a new implementation of API hashing

Thanks for the tip, I tested this using the same scripted test in dotty and it failed, opened https://github.com/lampepfl/dotty/issues/12634

**Pull request merged**
