### PR TITLE
Merge 1.2.x with 1.x

### PR DESCRIPTION
**Pull request by jvican**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.x&zinc=pull/574/head&io=1.x&librarymanagement=1.x&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by jvican** [comment]
I'm merging this as soon as CI is passing as I'll be adding some changes in 1.x that depend on this.

**Comment by jvican** [comment]
Something is not looking good:

```
:::: WARNINGS
11s
122
		module not found: org.scala-sbt#zinc-testing_2.12;1.2.0
11s
124
	==== local: tried
11s
126
	  /drone/.ivy2/local/org.scala-sbt/zinc-testing_2.12/1.2.0/ivys/ivy.xml
11s
128
	  -- artifact org.scala-sbt#zinc-testing_2.12;1.2.0!zinc-testing_2.12.jar:
11s
130
	  /drone/.ivy2/local/org.scala-sbt/zinc-testing_2.12/1.2.0/jars/zinc-testing_2.12.jar
11s
132
	==== Maven Central: tried
11s
134
	  https://repo1.maven.org/maven2/org/scala-sbt/zinc-testing_2.12/1.2.0/zinc-testing_2.12-1.2.0.pom
11s
136
	  -- artifact org.scala-sbt#zinc-testing_2.12;1.2.0!zinc-testing_2.12.jar:
11s
138
	  https://repo1.maven.org/maven2/org/scala-sbt/zinc-testing_2.12/1.2.0/zinc-testing_2.12-1.2.0.jar
11s
140
	==== typesafe-ivy-releases: tried
11s
142
	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/zinc-testing_2.12/1.2.0/ivys/ivy.xml
11s
144
	==== sbt-ivy-snapshots: tried
11s
146
	  https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/zinc-testing_2.12/1.2.0/ivys/ivy.xml
11s
148
		::::::::::::::::::::::::::::::::::::::::::::::
11s
150
		::          UNRESOLVED DEPENDENCIES         ::
11s
152
		::::::::::::::::::::::::::::::::::::::::::::::
11s
154
		:: org.scala-sbt#zinc-testing_2.12;1.2.0: not found
11s
156
		::::::::::::::::::::::::::::::::::::::::::::::
11s
160
:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
11s
161
unresolved dependency: org.scala-sbt#zinc-testing_2.12;1.2.0: not found
```

**Comment by jvican** [comment]
Closing temporarily. Will re-open as soon as it's clear what's up here.

**Pull request closed without merging**
