### PR TITLE
Optionally turning on customized file manager

### PR DESCRIPTION
**Pull request by peiyuwang**
This addresses #185 

Implementation detail:

Adding an additional parameter is a little clunky, rather, this PR combines existing param `classFileManager` and the new boolean `useCustomizedFileManager` into `IncToolOptions` because both are for inc compile used for java tools.

As a by product, by using `Maybe<ClassFileManager>` allows to kill `NoopClassFileManager`.

If this looks ok I will make the downstream change in https://github.com/sbt/sbt, probably replace https://github.com/sbt/sbt/pull/2791

### CODE REVIEW

**Comment by peiyuwang** [comment]
@eed3si9n can you review this? mostly done with testing this change (along with the earlier #181 ), ready to ask for a new release if this PR goes in

**Comment by eed3si9n** [comment]
So the title of this PR should be flipped to optionally turning "on" if the default is off?

**Comment by peiyuwang** [comment]
yea, :) fixed

**Comment by eed3si9n** [comment]
Merged! Thanks for the contribution :)

**Comment by peiyuwang** [comment]
cool thanks!

I will update https://github.com/sbt/sbt/pull/2791

**Pull request merged**
