### PR TITLE
Avoid regex in UsedName for the common case of names without newlines

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

**Review by dwijnand — DISMISSED** [review]

**Comment by jvican** [comment]
Can you rebase on top of latest 1.x?

**Review by jvican — DISMISSED** [review]

**Comment by retronym** [comment]
done

**Comment by dwijnand** [comment]
I think this should target the 1.2.x branch.

**Comment by jvican** [comment]
We’ve been merging things in 1.x because it simplifies maintenance and there’s no need to do periodic merges from 1.2x to 1.x. This is important for me because I don’t depend on the Scala-sbt artifacts in bloop and I need to work with the latest master. In general I think It’s better that we merge everything to 1.x and then you cherry pick for 1.2.x.

**Comment by dwijnand** [comment]
In the past cherry-picking became a nightmare, in the 0.13/1.x branch split of sbt/sbt. IMO the periodic merging should be automated (either on each 1.y.x PR merge, or nightly). I don't like when the patch fix branches have fixes not in "master" too.

**Comment by jvican** [comment]
I’ll be working on the 1.x branch because my next changes should not be added to 1.2.x, you can merge this in 1.2.x but please make sure you submit a PR to merge it to 1.x too @dwijnand

**Comment by eed3si9n** [comment]
@dwijnand @jvican I opened https://discuss.lightbend.com/t/patching-strategy/1924 to discuss patching strategy.

**Comment by jvican** [comment]
Let's land this in `develop` then :smile:

**Review by jvican — APPROVED** [review]
LGTM

**Pull request merged**
