### PR TITLE
Fix blog link in CONTRIBUTING

### LINKED ISSUE #466: broken link
here 
https://github.com/sbt/zinc/blob/1.x/CONTRIBUTING.md

this
https://www.scala-lang.org/blog/2017/01/03/zinc-blog-post.html

should be
https://www.scala-lang.org/blog/2017/11/03/zinc-blog-1.0.html

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #466

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?zinc=pull/467/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by dwijnand** [comment]
Just fixing a 404 link here in a markdown file.. merging.

**Comment by eed3si9n** [comment]
👍

**Comment by jvican** [comment]
Thanks @dwijnand, I was the one that restarted the CI after the first try failed, but forgot to visit this PR again.

**Pull request merged**
