### PR TITLE
Throw when javadoc generation fails

### PR DESCRIPTION
**Pull request by raboof**
As discussed in #414. Unfortunately I haven't been able to run the tests,
as 'sbt clean publishBridges' already fails for me.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/625/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1251/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-pull/625/head-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1251/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@17b2737bbfbea9aa4980419001b58944d12ba714
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/625">pull/625/head       </A> | sbt/zinc@7420f9162535a1401f17aa0025c0c8dffdd08cc4
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@ca872a2561ee918e65a062569637a7e3261267a4
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@91071253d98e66331a7821278444ebf41544da20
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@2e0d2d920a9f11c1910f0a5d48a2ff6f2c57c44d

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=pull/625/head&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by raboof** [comment]
This looks like it may be a flakey test:
```
[sbt212-librarymanagement] NORMAL RESOLUTION TIME 1798
[sbt212-librarymanagement] FASTER RESOLUTION TIME 1490
[sbt212-librarymanagement] [info] ModuleResolversTest:
[sbt212-librarymanagement] [info] The direct resolvers in update options
[sbt212-librarymanagement] [info] - should skip the rest of resolvers *** FAILED ***
[sbt212-librarymanagement] [info]   1490 was not less than or equal to 1438.4 (ModuleResolversTest.scala:48)
```

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1252/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-pull/625/head-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1252/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@17b2737bbfbea9aa4980419001b58944d12ba714
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/625">pull/625/head       </A> | sbt/zinc@7420f9162535a1401f17aa0025c0c8dffdd08cc4
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@ca872a2561ee918e65a062569637a7e3261267a4
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@91071253d98e66331a7821278444ebf41544da20
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@2e0d2d920a9f11c1910f0a5d48a2ff6f2c57c44d

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=pull/625/head&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by eed3si9n** [comment]
Thanks @raboof!

Note: There's some test here. Maybe we can add a test for you if you can't - https://github.com/sbt/zinc/blob/develop/zinc-compile/src/test/scala/inc/DocSpec.scala

**Comment by raboof** [comment]
Thanks for the help on Gitter, I got the tests to work an added one that checks the javadoc tool indeed throws on an invalid Java input file, rather than failing silently without output.

**Review by eed3si9n — APPROVED** [review]

**Review by jvican — APPROVED** [review]
LGTM @raboof, thanks :smile:

**Pull request merged**
