### PR TITLE
Add IncOptions#skipJavac, to allow pipelining

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/842/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by eed3si9n** [comment]
I'm in the process of turning off javac in https://github.com/sbt/zinc/pull/843

**Comment by dwijnand** [comment]
Can that build on this?  I wouldn't mind getting this merged ASAP to help test the pipelining supported merged.  This is the one blocker.

**Comment by eed3si9n** [comment]
I don't think it makes sense to introduce a new flag for this purpose.

**Comment by dwijnand** [comment]
The alternative in #843 you're proposing is introducing a whole bunch of alternative, duplicate methods, which doesn't look leaps and bounds better.

But #843 with a `javaOnly` IncOption I think I'd be happy with.

**Comment by dwijnand** [comment]
Closing in favour of #843.

**Pull request closed without merging**
