### PR TITLE
Fix concurrent modification issue

### LINKED ISSUE #974: j.u.ConcurrentModificationException with Scala 2.13.{4,5} and Java sources
We get a `java.util.ConcurrentModificationException` when compiling code with zinc and Scala 2.13.4 or 2.13.5. The same code can be compiled successfully, when Scala 2.13.3 or older is used.

## steps

1. Clone the minimal reproducer project from: https://github.com/chikei/zinc-ConcurrentModificationException (https://github.com/chikei/zinc-ConcurrentModificationException/commit/96b0e904481cf82da8557ea7d18dfbc3302c546e)

2. run `sbt run`

## problem

Instead of compiling successfully, an `java.util.ConcurrentModificationException` is thrown.

<details>
<summary>The full output:</summary>

```
21:39:28 ⌁ θ62° lefou:~/work/tmp/zinc-ConcurrentModificationException master ± sbt run
[info] welcome to sbt 1.4.7 (AdoptOpenJDK Java 1.8.0_272)
[info] loading settings for project global-plugins from coursier.sbt,eclipse.sbt,idea.sbt,metals.sbt ...
[info] loading global plugins from /home/lefou/.sbt/1.0/plugins
[info] loading project definition from /home/lefou/work/tmp/zinc-ConcurrentModificationException/project
[info] loading settings for project zinc-concurrentmodificationexception from build.sbt ...
[info] set current project to zinc-concurrent (in build file:/home/lefou/work/tmp/zinc-ConcurrentModificationException/)
[info] compiling 1 Scala source to /home/lefou/work/tmp/zinc-ConcurrentModificationException/target/scala-2.13/classes ...
[warn] 2 deprecations (since 1.4.0); re-run with -deprecation for details
[warn] one warning found
[info] running example.MainClass 
[info] compiling 1 Java source to /tmp/zincClasses3378735785364370019 ...
[error] ## Exception when compiling 1 sources to /tmp/zincClasses3378735785364370019
[error] java.util.ConcurrentModificationException: mutation occurred during iteration
[error] scala.collection.mutable.MutationTracker$.checkMutations(MutationTracker.scala:43)
[error] scala.collection.mutable.MutationTracker$CheckedIterator.hasNext(MutationTracker.scala:59)
[error] scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error] scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error] scala.collection.AbstractIterable.foreach(Iterable.scala:919)
[error] sbt.internal.inc.ClassToAPI$.process(ClassToAPI.scala:34)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.readAPI$1(AnalyzingJavaCompiler.scala:180)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$23(AnalyzingJavaCompiler.scala:205)
[error] sbt.internal.inc.classfile.JavaAnalyze$.readInheritanceDependencies$1(JavaAnalyze.scala:194)
[error] sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$15(JavaAnalyze.scala:201)
[error] sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$15$adapted(JavaAnalyze.scala:110)
[error] scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error] scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error] scala.collection.AbstractIterable.foreach(Iterable.scala:919)
[error] scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
[error] sbt.internal.inc.classfile.JavaAnalyze$.apply(JavaAnalyze.scala:110)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$21(AnalyzingJavaCompiler.scala:205)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$21$adapted(AnalyzingJavaCompiler.scala:199)
[error] scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error] scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error] scala.collection.AbstractIterable.foreach(Iterable.scala:919)
[error] scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$19(AnalyzingJavaCompiler.scala:199)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:251)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:199)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$1(MixedAnalyzingCompiler.scala:98)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileJava(MixedAnalyzingCompiler.scala:61)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileJava0$1(MixedAnalyzingCompiler.scala:191)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:457)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:412)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:399)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] example.MainClass$.delayedEndpoint$example$MainClass$1(MainClass.scala:85)
[error] example.MainClass$delayedInit$body.apply(MainClass.scala:13)
[error] scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] scala.App.$anonfun$main$1(App.scala:76)
[error] scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error] scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error] scala.collection.AbstractIterable.foreach(Iterable.scala:919)
[error] scala.App.main(App.scala:76)
[error] scala.App.main$(App.scala:74)
[error] example.MainClass$.main(MainClass.scala:13)
[error] example.MainClass.main(MainClass.scala)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.Run.invokeMain(Run.scala:133)
[error] sbt.Run.execute$1(Run.scala:82)
[error] sbt.Run.$anonfun$runWithLoader$5(Run.scala:110)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
[error] sbt.TrapExit$App.run(TrapExit.scala:258)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] (run-main-0) java.util.ConcurrentModificationException: mutation occurred during iteration
[error] java.util.ConcurrentModificationException: mutation occurred during iteration
[error]         at scala.collection.mutable.MutationTracker$.checkMutations(MutationTracker.scala:43)
[error]         at scala.collection.mutable.MutationTracker$CheckedIterator.hasNext(MutationTracker.scala:59)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 8 s, completed 15.04.2021 21:42:15
```
</details>

## expectation

The compilation should succeed successfully.

## notes

We hit this issue in mill (https://github.com/com-lihaoyi/mill), which uses zinc to compile Scala and Java projects. This issue is a blocker to update to Scala 2.13.5, as we can't compile Mills codebase. See also discussion https://github.com/com-lihaoyi/mill/discussions/1278

The reproducer uses zinc 1.5.0 and fails with AdoptOpenJDK 1.8 as well as AdoptOpenJDK 11 on Linux.

It is a cut down version of our use of zinc in Mill (https://github.com/com-lihaoyi/mill/blob/master/scalalib/worker/src/ZincWorkerImpl.scala).

The repro was created by @chikei and has the following structure:

```
.
├── README.md
├── build.sbt
├── project
│   └── build.properties
└── src
    └── main
        ├── resources
        │   └── mill
        │       └── main
        │           └── client
        │               └── FileToStreamTailer.java  <-- The Java source file to compile
        └── scala
            └── example
                └── MainClass.scala  <-- A minimal App using the zinc compiler to compile the sources under resources

```

Here is a GH Actions workflow that shows the failing CI for mill: https://github.com/com-lihaoyi/mill/actions/runs/746276787

### PR DESCRIPTION
**Pull request by lefou**
May fix https://github.com/sbt/zinc/issues/974

Patch suggested by Guillaume Martres.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/975/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Review by eed3si9n — APPROVED** [review]
LGTM
Is there a reason this is a draft?

**Comment by lefou** [comment]
> LGTM
> Is there a reason this is a draft?

I couldn't get the whole test suite to run on my current machine and wanted to see the results of the CI.

What sbt settings or `.sbtopts` content do you use? I got a OOME for Metaspace.

**Comment by eed3si9n** [comment]
```
$ echo $SBT_OPTS
-Xms2048M -Xmx2048M -Xss2M
```

See also https://github.com/sbt/zinc/blob/develop/bin/run-ci.sh

**Comment by lefou** [comment]
Ok, I now got sbt to build and publishLocal, but I had to raise the Metaspace memory settings significantly. Anyways, looks like our reproducer for issue #974 can be fixed with this PR. A quick merge and new zinc release would be greatly appreciated, as it would unblock a Scala update in mill.

**Comment by lefou** [comment]
@eed3si9n Thank you for merging! Do you have an ETA for a new zinc release?

**Comment by eed3si9n** [comment]
Maybe this weekend or next?

**Pull request merged**
