### PR TITLE
[Fix] Make DiagnosticsReporter check scheme before converting to File targeting 1.3.x

### PR DESCRIPTION
**Pull request by lloydmeta**
Fixes https://github.com/sbt/sbt/issues/4305

This is https://github.com/sbt/zinc/pull/719 but targeting `1.3.x`

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.3.x&zinc=pull/723/head&io=1.3.x&librarymanagement=1.3.x&util=1.3.x&website=1.3.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Review by lloydmeta — COMMENTED** [review]
@eed3si9n seems like the build is failing in this target branch too.

**Comment by eed3si9n** [comment]
I've backported https://github.com/sbt/zinc/pull/726. Could you rebase against the 1.3.x head plz?

**Comment by lloydmeta** [comment]
> I've backported #726. Could you rebase against the 1.3.x head plz?

@eed3si9n done. build is passing as well.

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
