### PR TITLE
Update sbt modules, migrate to scalatest

### PR DESCRIPTION
**Pull request by Duhemm**
- Update sbt/util to 1.0.0-M3
- Update sbt/librarymanagement to 1.0.0-M2

Also, migrate the tests from specs2 to scalatest.

### CODE REVIEW

**Comment by eed3si9n** [comment]
Awesome

**Comment by eed3si9n** [comment]
Actually scalatest not fully converted. I should've reviewed more carefully..

**Comment by gkossakowski** [comment]
What was the reason to moe from specs2 to scalatest?

**Comment by eed3si9n** [comment]
ScalaTest seems to be more stable and depends less on community libraries.

**Comment by gkossakowski** [comment]
Ok. I'll port my tests for class-based deps to scalatest.

**Pull request merged**
