### PR TITLE
Test case for dependencies involving implicits and higher-kinds.

### PR DESCRIPTION
**Pull request by Krever**
This solves #339 . It turned out that the test is passing now(it was not in original commit to sbt).

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/341/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/77/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.0.x-pull/341/head-1.0-1.0-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/77/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | 1.0.x                | sbt/sbt@d464383722ef736376dc85e3f052826c6f627d23
  zinc              | pull/341/head        | sbt/zinc@bde9b92ad058e930f560c2ad45a8a43a35610aec
  io                | 1.0                  | sbt/io@21ed6ec2a2e33fd88a5f013f643d04fda26de4de
  librarymanagement | 1.0                  | sbt/librarymanagement@9d1b8de2ff4c89e96267308af5271288592ff0ad
  util              | 1.0                  | sbt/util@c76d2624f931a2b75453f39dcaaf750bf4282a44
  website           | 1.0.x                | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=1.0.x&zinc=pull/341/head&io=1.0&librarymanagement=1.0&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Review by jvican — APPROVED** [review]
LGTM, thanks for this contribution @Krever :smile:.
  
The dbuild error is not related to this issue, and since this PR does not change the API, it's fine to be merged with that error.

**Review by Duhemm — APPROVED** [review]
LGTM, congrats on the first contribution 🎉 !

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/341/head&deploy_to_bintray=false">this link.</A>

**Comment by dwijnand** [comment]
Cool :)

**Comment by typesafe-tools** [comment]
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/78/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.0.x-pull/341/head-1.0-1.0-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/78/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | 1.0.x                | sbt/sbt@d464383722ef736376dc85e3f052826c6f627d23
  zinc              | pull/341/head        | sbt/zinc@09626ebeeed86e86595df9fb2378aea0dac326f3
  io                | 1.0                  | sbt/io@21ed6ec2a2e33fd88a5f013f643d04fda26de4de
  librarymanagement | 1.0                  | sbt/librarymanagement@f3c0eb2e5868f01b4e2610cb95321e2e9816e72f
  util              | 1.0                  | sbt/util@c76d2624f931a2b75453f39dcaaf750bf4282a44
  website           | 1.0.x                | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=1.0.x&zinc=pull/341/head&io=1.0&librarymanagement=1.0&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

**Pull request merged**
