### PR TITLE
Fix #459: Upgrade protobuf to 3.7.0 to get rid of Java 9+ warnings

### LINKED ISSUE #459: Java 9 WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil
## steps

Run on Java 9.

## problem

```
[info] Compiling 1 Scala source to /root/work/hello/project/target/scala-2.12/sbt-1.0/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.4. Compiling...
[info]   Compilation completed in 9.719s.
[info] Done compiling.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/root/.sbt/boot/scala-2.12.4/org.scala-sbt/sbt/1.0.4-LOCAL1/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

## expectation

No warnings

## notes

See https://github.com/google/protobuf/issues/3781

### PR DESCRIPTION
**Pull request by smarter**
I have no idea if this is binary-compatible so fingers crossed.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/644/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1449/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-pull/644/head-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1449/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@354f85cecba4d5a165174e1471458940c523eda9
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/644">pull/644/head       </A> | sbt/zinc@bc7a8f5ba84403c7bfdc931a280b393300f481f4
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@0ae81420bab2ed35a64c1691ac206efc323c9973
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@6d35f329b6b6be8da467eefc399ba9fa6f6725c0
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@48574c204117a91a47d10e19c52826ec4e5195c3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=pull/644/head&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by smarter** [comment]
Looks like sbt doesn't compile with zinc master, so hard to test things more.

**Comment by eed3si9n** [comment]
I saw the drone job fail first, so I restarted it. Now it's green, so it's good to go, I think.
There's some changes that were made in IO that needs to propagate out for the Dbuild validation.

**Review by eed3si9n — APPROVED** [review]

**Review by jvican — APPROVED** [review]

**Pull request merged**
