### PR TITLE
Backport changes from several previous PRs

### PR DESCRIPTION
**Pull request by jvican**
This commit introduces changes to Scala 2.10 sources from the following
PRs:

* https://github.com/sbt/zinc/pull/225
* https://github.com/sbt/zinc/pull/216
* https://github.com/sbt/zinc/pull/206
* https://github.com/sbt/zinc/pull/221

It also removes a stub for 2.8 compatibility in `DelegatingReporter`.
Support for Scala 2.8 compatibility is not already maintained it.

### CODE REVIEW

**Comment by jvican** [comment]
I'll be basing my next PR to fix ASF in these changes because they bring Scala 2.10.x and >= 2.11.x up to date. Changes to the type traverser require changes in the compiler bridge test suite, that is shared by both versions.
  
Can we merge this soon and I'll push my changes to fix ASF?

**Comment by dwijnand** [comment]
@jvican Correct me if I'm wrong, but isn't the difference in source code between 2.10 and non-2.10 minimal? Would it not be possible to reduce the difference in source code? Instead of this business of having to "backport" changes in the same repo on the same branch.

Also, why is this even necessary post-merge? Don't we test zinc under 2.10 in CI? Why didn't it fail Travis CI?

**Comment by jvican** [comment]
@dwijnand Indeed, differences are minimal and very focused, they could be abstracted away. But this requires time. I won't be able to do such thing short-term. Also, it's not clear it's possible.
  
> Also, why is this even necessary post-merge? Don't we test zinc under 2.10 in CI? Why didn't it fail Travis CI?
  
My changes to `ExtractUsedNames` and `Dependency` haven't been pushed yet, they are local, so you won't notice they fail. These changes affect correctness, and that's why keeping an old, unmodified version of Zinc in 2.10 will make some tests fail -- the testing suite is shared.

**Comment by dwijnand** [comment]
No, what I mean is take #216 for example. It changes just the non-2.10 version of compiler-bridge (https://github.com/sbt/zinc/pull/216/files#diff-078aa14c94ffc4285ff1c49d727f9a67).

So either:
1. We're not running tests against 2.10 zinc, or
2. There's no test for the changes made in the PR

If it's (2) it isn't great, but if it's (1) it's concerning.

Personally I would prefer if we minimised the changes instead of backporting them. I'll try and find time to work on that, @jvican, I don't mean to burden you.

**Comment by dwijnand** [comment]
#233

**Comment by jvican** [comment]
The reason for which this PR fails demonstrates that we're indeed testing the 2.10 sources. The PRs that you mention don't affect correctness of the compiler, that is, the underlying logic -- they just change the code to make it more performant.
  
> Personally I would prefer if we minimised the changes instead of backporting them.
  
I would also. But since this is a blocker for me to continue my work on Zinc, which will finish in one week, I propose that we merge these changes. We can minimise the differences later down the road.

**Comment by jvican** [comment]
I've just updated this PR to see if now there's more luck with CI. Previous failing test here: https://travis-ci.org/sbt/zinc/jobs/203844727.

**Comment by dwijnand** [comment]
> Refinement classes do not have byte code representation and it fails later on (we still depends on parents of refinement)

(from https://github.com/sbt/zinc/pull/216/files#r99321507)

would imply correctness not performance.

**Comment by jvican** [comment]
I wonder what the root of @romanowski's problem was, because yeah, that change was provided without any test. Hopefully it's just an exception. I think it's safe because we're still traversing the declarations and the parents of the `RefinedType`.

**Comment by dwijnand** [comment]
> But since this is a blocker for me to continue my work on Zinc, which will finish in one week..

I see. I'll work on it tomorrow then.

**Comment by romanowski** [comment]
@jvican I know, I should write a test case for this when I spot a problem. Sorry for that.

I can try to reproduce it if you really like but it may take me a while (and I am quite busy this week).

**Comment by jvican** [comment]
@romanowski Don't worry, I don't think it's important :wink:.

**Comment by dwijnand** [comment]
@jvican I've started making progress, but 2 things: (1) it's not ready yet, and (2) it might involve changing some paths, maybe (I'm not done).

I wouldn't want to further delay your work _as well as_ mess you up by moving files around.

So let's merge.

**Review by dwijnand — APPROVED** [review]

**Comment by jvican** [comment]
Thanks, if you're still stuck on this after one week, I can help you out. The changes are not trivial and they may affect performance. You'll probably need to do some tricks with implicit resolution for it to work correctly.

**Pull request merged**
