### PR TITLE
[wip] Bump to sbt 1.0.0-M6

### PR DESCRIPTION
**Pull request by eed3si9n**
Ref https://github.com/sbt/zinc/pull/316

Benchmark is commented out until sbt-jmh is out http://dl.bintray.com/sbt/sbt-plugin-releases/pl.project13.scala/sbt-jmh/. Ref https://github.com/ktoso/sbt-jmh/issues/115

### CODE REVIEW

**Comment by ktoso** [comment]
0.2.26 released, please try it

**Comment by eed3si9n** [comment]
@ktoso is it supposed to be here? http://dl.bintray.com/sbt/sbt-plugin-releases/pl.project13.scala/sbt-jmh/ I am not seeing it.

**Comment by ktoso** [comment]
It is here: https://bintray.com/ktosopl/sbt-plugins/sbt-jmh/0.2.26#files/pl.project13.scala%2Fsbt-jmh%2Fscala_2.10%2Fsbt_0.13%2F0.2.26%2Fjars / http://dl.bintray.com/sbt/sbt-plugin-releases/pl.project13.scala/sbt-jmh/scala_2.10/sbt_0.13/0.2.26/

Hmm... should it have appeared under `scala_2.12`?
Is there something else I need to change in my build?

```
> sbtVersion
[info] 0.13.16-M1
> publishSigned
[warn] Credentials file /Users/ktoso/.sbt/sonatype.properties does not exist
[info] :: delivering :: pl.project13.scala#sbt-jmh;0.2.26 :: 0.2.26 :: release :: Tue Jun 27 16:12:49 JST 2017
[info] 	delivering ivy file to /Users/ktoso/code/sbt-jmh/plugin/target/scala-2.10/sbt-0.13/ivy-0.2.26.xml
[info] Packaging /Users/ktoso/code/sbt-jmh/plugin/target/scala-2.10/sbt-0.13/sbt-jmh-0.2.26.jar ...
[info] Done packaging.
{"message":"Unable to upload files: An artifact with the path 'pl.project13.scala/sbt-jmh/scala_2.10/sbt_0.13/0.2.26/jars/sbt-jmh.jar' already exists"}
```

**Comment by jvican** [comment]
I propose to close this. I've updated my original PR: https://github.com/sbt/zinc/pull/316.
  
Thanks for the release @ktoso :smile:.

**Comment by ktoso** [comment]
So is that publish correct? I thought that it was supposed to be Scala 2.12 now hm

**Comment by jvican** [comment]
Wow, really weird. Was working for me locally, but sbt is failing to resolve sbt-jmh in the CI: https://platform-ci.scala-lang.org/sbt/zinc/27/1.

**Comment by jvican** [comment]
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
65s
231
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
65s
232
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
65s
233
[warn] 	:: pl.project13.scala#sbt-jmh;0.2.26: not found
65s
234
[warn] 	:: com.lucidchart#sbt-scalafmt;0.4.0-M1: not found
65s
235
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
65s
236
[warn] 
65s
237
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
65s
238
[warn] 		pl.project13.scala:sbt-jmh:0.2.26 (scalaVersion=2.12, sbtVersion=1.0.0-M6)
65s
239
[warn] 		com.lucidchart:sbt-scalafmt:0.4.0-M1 (scalaVersion=2.12, sbtVersion=1.0.0-M6)
65s
240
[warn] 
65s
241
[warn] 	Note: Unresolved dependencies path:
65s
242
[warn] 		pl.project13.scala:sbt-jmh:0.2.26 (scalaVersion=2.12, sbtVersion=1.0.0-M6) (/drone/src/github.com/sbt/zinc/project/plugins.sbt#L4-5)
65s
243
[warn] 		  +- default:zinc-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0.0-M6)
65s
244
[warn] 		com.lucidchart:sbt-scalafmt:0.4.0-M1 (scalaVersion=2.12, sbtVersion=1.0.0-M6) (/drone/src/github.com/sbt/zinc/project/plugins.sbt#L5-6)
65s
245
[warn] 		  +- default:zinc-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0.0-M6)
65s
246
[error] (*:update) sbt.internal.librarymanagement.ResolveException: unresolved dependency: pl.project13.scala#sbt-jmh;0.2.26: not found
```

**Comment by jvican** [comment]
@ktoso Problem is that you have released the 2.10 artifact instead of the 2.12 artifact. Have you done `^ publishSigned` or just `publish`? It's important to use `^` to execute that task over all the sbt versions.

**Comment by ktoso** [comment]
That's what I was asking about ;)
Will do then

**Comment by ktoso** [comment]
Done

**Comment by jvican** [comment]
Eh voilà, thanks @ktoso. Progress happening here: https://platform-ci.scala-lang.org/sbt/zinc/28/1.
  
By the way, downloading sbt 1.0.0-M6 from scratch is really, really fast (in comparison with sbt 0.13.16). It's 24 seconds.

**Comment by jvican** [comment]
Closing this, progress happening in the original PR.

**Comment by jvican** [comment]
FYI @olafurpg tells me that previous sbt 0.13.x versions took ~300 seconds.

**Comment by eed3si9n** [comment]
Reopening this since https://github.com/sbt/zinc/pull/316 hasn't passed the PR validation yet.

**Pull request closed without merging**
