### PR TITLE
Drop Contraband to model Build/Project

### PR DESCRIPTION
**Pull request by dwijnand**
Trading 175 deletions for 23 insertions? Yes please.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/329/head&deploy_to_bintray=false">this link.</A>

**Comment by dwijnand** [comment]
This is failing because using LList I can't read

```json
{
  "projects": [
    {
      "name": "use",
      "scalaVersion": "2.12.1"
    },
    {
      "name": "dep",
      "scalaVersion": "2.12.1"
    }
  ]
}
```

Enhancement proposed in https://github.com/eed3si9n/sjson-new/pull/61.

**Comment by eed3si9n** [comment]
> Trading 175 deletions for 23 insertions? Yes please.

That number is bloated since the human-written part is 15 lines of Contraband schema

```diff
-package sbt.internal.inctest
-@target(Scala)
-@codecPackage("sbt.internal.inctest")
-@fullCodec("JsonProtocol")
-
-type Build {
-  projects: [sbt.internal.inctest.Project]
-}
-
-type Project {
-  name: String!
-  dependsOn: [String] @since("0.1.0")
-  in: java.io.File @since("0.1.0")
-  scalaVersion: String @since("0.1.0")
-}
```

Why maintain codecs (for internal testing tool) when you can generate them?

**Comment by dwijnand** [comment]
> That number is bloated since the human-written part is 15 lines of Contraband schema

The human-read part is still 175 lines though..

> Why maintain codecs (for internal testing tool) when you can generate them?

I wish sjson-new had better support for generating JSON formats from case classes. Is there anything more concise than what I'm currently doing?

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/329/head&deploy_to_bintray=false">this link.</A>

**Comment by eed3si9n** [comment]
> I wish sjson-new had better support for generating JSON formats from case classes. Is there anything more concise than what I'm currently doing?

I think Yoshida san contributed that in - https://github.com/eed3si9n/sjson-new/pull/52

**Comment by dwijnand** [comment]
Neato, I'd forgotten about that.

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/329/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/329/head&deploy_to_bintray=false">this link.</A>

**Comment by dwijnand** [comment]
So this is (rebased and) green. And using the latest and greatest sjson-new impl it's down to 14 lines.

WDYT about the change?

**Review by jvican — APPROVED** [review]
This is a great change, I like it. LGTM.

**Review by Duhemm — APPROVED** [review]
Indeed we don't need Contraband for that 👍

**Pull request merged**
