### PR TITLE
Finish dropping LM/Ivy/zinc-ivy-integration

### PR DESCRIPTION
**Pull request by dwijnand**
I've downstreamed the integration code to sbt in https://github.com/sbt/sbt/pull/4617.  However that requires a fresh release of Zinc.

I've kept the same class names as they are in Zinc, while changing the artifactId., so it's safer to drop these classes here before cutting a release of Zinc, to avoid any classpath clashes downstream.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/658/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1537/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4617/head-pull/658/head-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1537/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4617">pull/4617/head      </A> | sbt/sbt@9674e4a6e9c45eab96331a9af21715255d26179c
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/658">pull/658/head       </A> | sbt/zinc@0b6470f2b8558e5c8b77e2942f02aca19e3bbad8
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@ca966bcd6c73400b11c7a78e8604ea211f32e3d8
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@f073dde812848ef443619578f55e290f3863bcaa
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@473d42ac782f9449dbd7c7940a67208abbff1861

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4617/head&zinc=pull/658/head&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1538/console">is in progress...</a>

**Review by eed3si9n — APPROVED** [review]

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4617/head-pull/658/head-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1538/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4617">pull/4617/head      </A> | sbt/sbt@7466ee4913d5281b99130c217c7bac02347adb76
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/658">pull/658/head       </A> | sbt/zinc@0b6470f2b8558e5c8b77e2942f02aca19e3bbad8
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@ca966bcd6c73400b11c7a78e8604ea211f32e3d8
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@f073dde812848ef443619578f55e290f3863bcaa
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@473d42ac782f9449dbd7c7940a67208abbff1861

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4617/head&zinc=pull/658/head&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1539/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4617/head-pull/658/head-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1539/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4617">pull/4617/head      </A> | sbt/sbt@7466ee4913d5281b99130c217c7bac02347adb76
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/658">pull/658/head       </A> | sbt/zinc@0b6470f2b8558e5c8b77e2942f02aca19e3bbad8
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@ca966bcd6c73400b11c7a78e8604ea211f32e3d8
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@f073dde812848ef443619578f55e290f3863bcaa
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@473d42ac782f9449dbd7c7940a67208abbff1861

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4617/head&zinc=pull/658/head&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by jvican — APPROVED** [review]
LGTM :+1: We're depending on all of this but I guess it's not a big deal. We'll most likely need to copy paste it to be able to resolve the bridge sources in the short-term.

**Comment by dwijnand** [comment]
> We're depending on all of this but I guess it's not a big deal. We'll most likely need to copy paste it to be able to resolve the bridge sources in the short-term.

"We" who? Copy paste where?  (I'm moving this code into https://github.com/sbt/sbt/pull/4617 so for Zinc's build will continue to use this functionality in its build)

**Comment by jvican** [comment]
I meant that we (Scala Center) will need to copy paste this code to bloop because we use all of these APIs for now.

**Pull request merged**
