### PR TITLE
Add failing test case for #559

### PR DESCRIPTION
**Pull request by OlegYch**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/590/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by jvican** [comment]
Can you move the file `test` to `pending` so that CI passes and we can merge this? I'll be looking into this today, and I'll submit another PR with a fix.

**Comment by OlegYch** [comment]
@jvican done

**Comment by jvican** [comment]
I'm closing this and instead of opening a pull request with a better reproduction of the issue + a fix.

**Pull request closed without merging**
