### PR TITLE
Remove unused 'resident' option

### LINKED ISSUE #340: Remove any trace of the resident compiler
The resident compiler was a thing, some time ago, and the idea was abandoned because it was deemed to be hard. From Grzgorz's description of the upstream sbt issue:
```
Inspired by: http://stackoverflow.com/questions/23278316/experimental-support-for-keeping-the-scala-compiler-resident-with-sbt-resident-l

The conclusion from our experiments with resident compilation is that the feature is very difficult to implement (due to Scala compiler being not designed for that use case). The benefit of resident compilation turned out to be much smaller than anticipated.

For those reasons, we don't plan to work on resident compilation and we should remove any references from sbt to it.
```
  
The goal of this ticket is to grep for "resident" and resident compilation and remove any trace of it, both in the APIs and docs.
  
This is a ticket ported from sbt: https://github.com/sbt/sbt/issues/1287.

### PR DESCRIPTION
**Pull request by lukeindykiewicz**
Remove unused 'resident' option, fixes #340

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @lukeindykiewicz,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/345/head&deploy_to_bintray=false">this link.</A>

**Comment by jvican** [comment]
@lukeindykiewicz Thanks for the contribution, having a look at it now, we'll see what the CI reports :smile:.

**Comment by lukeindykiewicz** [comment]
CLA signed

**Review by Duhemm — DISMISSED** [review]
LGTM, and welcome to Zinc @lukeindykiewicz!

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/345/head&deploy_to_bintray=false">this link.</A>

**Comment by jvican** [comment]
It seems this requires a manual rebase, I'll do it as soon as I can.

**Review by eed3si9n — DISMISSED** [review]

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/345/head&deploy_to_bintray=false">this link.</A>

**Review by jvican — APPROVED** [review]
I just rebased manually, LGTM.

**Review by Duhemm — APPROVED** [review]
LGTM!

**Comment by jvican** [comment]
Merging, things haven't changed here, it was a clean rebase. /cc @eed3si9n

**Pull request merged**
