### PR TITLE
Use scripted core from sbt/util

### PR DESCRIPTION
**Pull request by eed3si9n**
Continuation of #40

### CODE REVIEW

**Comment by eed3si9n** [comment]
@Duhemm could you go over the pending scripted tests and find tests that can be added back because `run` exist?

**Comment by Duhemm** [comment]
@eed3si9n Sure

**Comment by Duhemm** [comment]
@eed3si9n I addressed your comments about the `run` task. Is it worth redirecting `System.out` and `System.err` to the logger?

**Comment by eed3si9n** [comment]
>  Is it worth redirecting System.out and System.err to the logger?

As long as the test works, I don't care much about the side effects.

**Comment by Duhemm** [comment]
@eed3si9n I surprisingly finally succeeded at reproducing the issue on my machine, and to "fix it" by sleeping after each file command.

**Comment by eed3si9n** [comment]
@Duhemm o wow.

**Comment by dwijnand** [comment]
I merged #57, which disabled `source-dependencies/nested-case-class`, which you said you'd then re-enable here, so here's me reminding you.

**Comment by eed3si9n** [comment]
I'm going to merge this as is for now in the hopes to merge other pending pull requests.

**Pull request merged**
