### PR TITLE
Thread-safe analysis callback

### LINKED ISSUE #405: Provide a thread-safe version of `AnalysisCallback`
`AnalysisCallback` is as of now not thread-safe. In @dragos's words:
>  Since we run several workers at the same time, and each worker has its own Global and analysis extraction logic, they perform updates concurrently. We used to override the compileIncrementalTask and fork some parts of Sbt to get to call our own implementation, but I think there should be a cleaner way, especially since xscbti.AnalysisCallback is an interface so it would be nice to be able to provide a different implementation.
  
This feature enables future parallel Scala compilers (like [Hydra](https://www.triplequote.com/hydra/)) to use the incremental compiler out of the box.
  
The place where the implementation should be provided is https://github.com/sbt/zinc/blob/1.x/internal/zinc-core/src/main/scala/sbt/internal/inc/Compile.scala, probably in an independent file.
  
The tests can be added in the `zincCore` project.

### PR DESCRIPTION
**Pull request by dotta**
Fixes #405

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/626/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Review by eed3si9n — APPROVED** [review]
LGTM

**Comment by dotta** [comment]
@jvican Could you have a look? I'm going to be away from Friday on and I'd really appreciate to have this merged before there are conflicts. Thanks!

**Review by jvican — APPROVED** [review]
LGTM :smile: thanks @dotta!

**Comment by dotta** [comment]
Whohooo! 🍾

**Pull request merged**
