### PR TITLE
Preserve jar order in ScalaInstance.otherJars

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?zinc=pull/411/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?zinc=pull/411/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Review by jvican — APPROVED** [review]
LGTM @dwijnand. I've added a commit adding an explicit type annotation for `otherJars`, so that its type doesn't change if `allJars` ever changes the type.
  
Merge if you feel comfortable with this new addition.

**Comment by dwijnand** [comment]
Good addition.

**Pull request merged**
