### PR TITLE
Make the zincPersist API public

### PR DESCRIPTION
**Pull request by jvican**
This PR depends on https://github.com/sbt/zinc/pull/351.

It adds the Java-friendly API to manipulate serialization/deserialization of
analysis files. It's a blocker for RC.
  
1. `AnalysisStore`. To allow users to implement their own way to back analysis
   files.
2. `AnalysisContents`. To allow API evolution of the return type of `set` in
   `AnalysisStore`. It replaces the previous tuple.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/354/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/354/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/354/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/354/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/354/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/354/head&deploy_to_bintray=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/354/head&deploy_to_bintray=false">this link.</A>

**Comment by eed3si9n** [comment]
Is there a ripple PR for this?

**Comment by jvican** [comment]
No, that will be ready tomorrow.

**Review by eed3si9n — CHANGES_REQUESTED** [review]
Waiting on ripple PR.
Otherwise LGTM

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/354/head&deploy_to_bintray=false">this link.</A>

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
