### PR TITLE
Re-enable IncrementalTest as ignored.

### PR DESCRIPTION
**Pull request by stuhood**
See https://github.com/sbt/zinc/issues/152: this re-enables IncrementalTest as ignored for now. More work will be necessary in order to sync up the AnalysisCallback implementations, but there are some passing tests, and this will help to minimize compiler-checkable bitrot.

### CODE REVIEW

**Comment by eed3si9n** [comment]
These are commented out because we opted for using scripted tests - https://github.com/sbt/zinc/tree/1.0/zinc/src/sbt-test

**Comment by jvican** [comment]
What's the status of this @eed3si9n ? Should this PR be closed since the decision to favour scripted tests was already taken?

**Comment by eed3si9n** [comment]
Yea. Let's close it for now.

**Comment by romanowski** [comment]
@eed3si9n if we don't want this tests anymore can we remove it from codebase with all its utils? I don't think that having whole file commented out and some dead code will help us anywhere. We can keep link to this (or any other) revision in e.g. comment somewhere if for some reason this code would be needed (but IMHO we can just remove all dead code).

@jvican  @stuhood WDYT?

**Comment by eed3si9n** [comment]
Yea. I'm fine with that. We can always dig it out of the git history.

**Comment by stuhood** [comment]
+1

On Feb 9, 2017 12:58 PM, "eugene yokota" <notifications@github.com> wrote:

Yea. I'm fine with that. We can always dig it out of the git history.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sbt/zinc/pull/153#issuecomment-278771669>, or mute the
thread

**Pull request closed without merging**
