### PR TITLE
[2.x] Merge 1.x branch into 2.x

### PR DESCRIPTION
**Pull request by Friendseeker**
Contains changes up to 0787c42

### CODE REVIEW

**Comment by Friendseeker** [comment]
CI / test (ubuntu-latest, 21, 6) (pull_request) failure is expected. `AnalysisFormatBenchmark` is currently broken on develop branch.

Safe to ignore that failure. After the PR is merged the CI issue would resolve itself.

**Comment by Friendseeker** [comment]
@eed3si9n Should I maintain this PR branch to track the latest changes from both `develop` and `1.10.x` branch (and maybe make a new PR that merges 1.10.x to develop biweekly) or would it be more preferable if I forward port each 1.10.x PR separately?

**Comment by eed3si9n** [comment]
> Should I maintain this PR branch to track the latest changes from both develop and 1.10.x branch (and maybe make a new PR that merges 1.10.x to develop biweekly) or would it be more preferable if I forward port each 1.10.x PR separately?

If possible, we should go with making the merge PR at whatever the cadence, than cherry pick one by one.

**Comment by eed3si9n** [comment]
Is this one of the concurrency issues?:

```scala
[error] ERROR: org.openjdk.jmh.runner.RunnerException: Benchmark caught the exception
[error] 	at org.openjdk.jmh.runner.Runner.runBenchmarks(Runner.java:572)
[error] 	at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:309)
[error] 	at org.openjdk.jmh.runner.Runner.run(Runner.java:208)
[error] 	at org.openjdk.jmh.Main.main(Main.java:71)
[error] Caused by: org.openjdk.jmh.runner.BenchmarkException: Benchmark error during the run
[error] 	at org.openjdk.jmh.runner.BenchmarkHandler.runIteration(BenchmarkHandler.java:440)
[error] 	at org.openjdk.jmh.runner.BaseRunner.runBenchmark(BaseRunner.java:262)
[error] 	at org.openjdk.jmh.runner.BaseRunner.runBenchmark(BaseRunner.java:233)
[error] 	at org.openjdk.jmh.runner.BaseRunner.doSingle(BaseRunner.java:138)
[error] 	at org.openjdk.jmh.runner.BaseRunner.runBenchmarksForked(BaseRunner.java:75)
[error] 	at org.openjdk.jmh.runner.ForkedRunner.run(ForkedRunner.java:72)
[error] 	at org.openjdk.jmh.runner.ForkedMain.main(ForkedMain.java:86)
[error] 	Suppressed: Error wrapping InputStream in GZIPInputStream: java.util.zip.ZipException: Not in GZIP format
[error] 		at sbt.internal.io.ErrorHandling$.translate(ErrorHandling.scala:21)
[error] 		at sbt.io.WrapUsing.open(Using.scala:44)
[error] 		at sbt.io.Using.apply(Using.scala:26)
[error] 		at sbt.internal.inc.consistent.ConsistentFileAnalysisStore$AStore.unsafeGet(ConsistentFileAnalysisStore.scala:105)
[error] 		at xsbt.AnalysisFormatBenchmark.read(AnalysisFormatBenchmark.scala:138)
```

**Comment by Friendseeker** [comment]
> Is this one of the concurrency issues?:
> 
> 
> 
> ```scala
> 
> [error] ERROR: org.openjdk.jmh.runner.RunnerException: Benchmark caught the exception
> 
> [error] 	at org.openjdk.jmh.runner.Runner.runBenchmarks(Runner.java:572)
> 
> [error] 	at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:309)
> 
> [error] 	at org.openjdk.jmh.runner.Runner.run(Runner.java:208)
> 
> [error] 	at org.openjdk.jmh.Main.main(Main.java:71)
> 
> [error] Caused by: org.openjdk.jmh.runner.BenchmarkException: Benchmark error during the run
> 
> [error] 	at org.openjdk.jmh.runner.BenchmarkHandler.runIteration(BenchmarkHandler.java:440)
> 
> [error] 	at org.openjdk.jmh.runner.BaseRunner.runBenchmark(BaseRunner.java:262)
> 
> [error] 	at org.openjdk.jmh.runner.BaseRunner.runBenchmark(BaseRunner.java:233)
> 
> [error] 	at org.openjdk.jmh.runner.BaseRunner.doSingle(BaseRunner.java:138)
> 
> [error] 	at org.openjdk.jmh.runner.BaseRunner.runBenchmarksForked(BaseRunner.java:75)
> 
> [error] 	at org.openjdk.jmh.runner.ForkedRunner.run(ForkedRunner.java:72)
> 
> [error] 	at org.openjdk.jmh.runner.ForkedMain.main(ForkedMain.java:86)
> 
> [error] 	Suppressed: Error wrapping InputStream in GZIPInputStream: java.util.zip.ZipException: Not in GZIP format
> 
> [error] 		at sbt.internal.io.ErrorHandling$.translate(ErrorHandling.scala:21)
> 
> [error] 		at sbt.io.WrapUsing.open(Using.scala:44)
> 
> [error] 		at sbt.io.Using.apply(Using.scala:26)
> 
> [error] 		at sbt.internal.inc.consistent.ConsistentFileAnalysisStore$AStore.unsafeGet(ConsistentFileAnalysisStore.scala:105)
> 
> [error] 		at xsbt.AnalysisFormatBenchmark.read(AnalysisFormatBenchmark.scala:138)
> 
> ```
> 
> 

The failure is an unrelated expected issue. The cause of it is that on develop branch, the zips used by benchmark are in text analysis format (which are not Gzip compressed), yet on develop branch, the benchmark code calls `FileAnslysisStore.binary` to fetch the text analysis zips, causing the exception.

The exception should resolve itself after the forward merge.

**Comment by eed3si9n** [comment]
I want to get this merged to 2.x. Could we comment out the failing benchmark?

**Comment by Friendseeker** [comment]
> I want to get this merged to 2.x. Could we comment out the failing benchmark?

Done!

**Pull request merged**
