### PR TITLE
Package object and implicit problem repro

### PR DESCRIPTION
**Pull request by romanowski**

### CODE REVIEW

**Comment by jvican** [comment]
Can we name the test `package-object-implicit-shading`?

**Comment by romanowski** [comment]
@jvican sure

**Review by jvican — APPROVED** [review]
LGTM.

@eed3si9n You can merge this.

**Comment by eed3si9n** [comment]
Let me test the Approve retraction.

**Review by eed3si9n — APPROVED** [review]

**Review by eed3si9n — CHANGES_REQUESTED** [review]
So the only way to retract approval is to request changes?

**Review by eed3si9n — APPROVED** [review]

**Comment by romanowski** [comment]
I planned to fix @jvican comments so I can still do that (on other PR). Just let me know.

**Comment by jvican** [comment]
Oh, I didn't realise those were missing. Don't worry about that, I'll make it myself.

**Pull request merged**
