### PR TITLE
fix getDecoder

### PR DESCRIPTION
**Pull request by jilen**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.1.x&zinc=pull/502/head&io=1.1.x&librarymanagement=1.1.x&util=1.1.x&website=1.1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/500/console">is in progress...</a>

**Comment by eed3si9n** [comment]
Thanks!
Looks like this got in https://github.com/sbt/zinc/commit/2b875dbf52062093512d19dc7fa3bfdfcb727b6f.
Do you mind adding a test case somewhere around https://github.com/sbt/zinc/tree/1.x/internal/zinc-persist/src/test/scala/sbt/inc/text?

**Comment by eed3si9n** [comment]
```scala
 private[sbt] object Base64 {
   lazy val factory: () => Base64 = {
     try {
       new Java678Encoder().encode(Array[Byte]())
       () =>
         new Java678Encoder()
     } catch {
       case _: LinkageError =>
         () =>
           new Java89Encoder
     }
   }
 }
```

Does this mean we need Java 9 to test this?

**Comment by jilen** [comment]
@eed3si9n  Alternatively we can test the `Java89Encoder` class directly, but that also requires java 8 at least

**Comment by eed3si9n** [comment]
sbt 1.x requires Java 8, so that's no problem.

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.1.x-pull/502/head-1.1.x-1.1.x-1.1.x-1.1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/500/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.1.x">1.1.x               </A> | sbt/sbt@9a5b7bcf6d69df3d4fa4a92a0f2bdcc39940eb60
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/502">pull/502/head       </A> | sbt/zinc@0b3717d809691fec4f36b4d581c8a6c56db7d8c4
  io                | <A HREF="https://github.com/sbt/io/tree/1.1.x">1.1.x               </A> | sbt/io@13eb241853180bdbb0d009ce11db5443749615d2
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.1.x">1.1.x               </A> | sbt/librarymanagement@69fb352fa131d6b01646f690753219091018e2bb
  util              | <A HREF="https://github.com/sbt/util/tree/1.1.x">1.1.x               </A> | sbt/util@9f12566a51a24388b28a6ba0986878834a262be3
  website           | <A HREF="https://github.com/sbt/website/tree/1.1.x">1.1.x               </A> | 

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.1.x&zinc=pull/502/head&io=1.1.x&librarymanagement=1.1.x&util=1.1.x&website=1.1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by jilen** [comment]
@eed3si9n  I've add a test case but that seems making nosense, is that ok ?

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
Would the test fail if you revert your fix? If so that's something.

**Review by jvican — APPROVED** [review]
LGTM, trusting the obvious syntactic error.

**Review by dwijnand — APPROVED** [review]
without the fix:

```scala
> zincPersist/testOnly sbt.inc.text.Base64Specification
[info] ! Base64.java89: Exception raised on property evaluation.
[info] > ARG_0: [B@18e5de43
[info] > Exception: java.lang.IllegalArgumentException: java.lang.ClassCastException@5433d119
[info] + Base64.java678: OK, passed 100 tests.
[info] ScalaCheck
[info] Failed: Total 2, Failed 0, Errors 1, Passed 1
[info] ScalaTest
[info] Run completed in 216 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
```

with the fix

```scala
> zincPersist/testOnly sbt.inc.text.Base64Specification
[info] + Base64.java678: OK, passed 100 tests.
[info] + Base64.java89: OK, passed 100 tests.
[info] ScalaCheck
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[info] ScalaTest
[info] Run completed in 217 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
```

**Pull request merged**
