### PR TITLE
Refactor the build^2

### PR DESCRIPTION
**Pull request by dwijnand**
First off this PR builds on #455 ("Merge 1.0.x into 1.x") because there are some build changes differences between 1.0.x and 1.x that I didn't want to merge 3 times (in each PR, and the merge of the PRs). However I can make this PR independent of that if that's better.

This PR is a re-take on @jvican's #428, with a number of adjustments, the two most important ones being (1) it targets the 1.x branch and (2) it uses bare name keys (rather than, e.g "Keys.version"). So it's @jvican's https://github.com/sbt/zinc/pull/429/commits/543dcb0d9aba092ec1e9fa11b46713277e81f59c commit from his #429 build PR.

If this PR is accepted and merged I'll take care of rebasing (and reviewing) @jvican's efforts in #429 so hopefully it too can be merged.

@jvican, please review my re-take here, I'm happy to explain my reasoning.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?zinc=pull/456/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by dwijnand** [comment]
Rebased on rebased #455.

**Comment by dwijnand** [comment]
With #455 merged, rebased on 1.x.

**Comment by dwijnand** [comment]
CI was failing because there were files in the 1.x branch that didn't have headers (and this is now enforced by CI). That's now fixed.

**Comment by jvican** [comment]
First, thank you for doing this. Tests are still failing. Second, I'm travelling these days -- I'll get back to this as soon as I'm home, and I will also reply to the pertinent open thread.

**Comment by dwijnand** [comment]
> First, thank you for doing this. Tests are still failing.

My pleasure.

> Second, I'm travelling these days -- I'll get back to this as soon as I'm home, and I will also reply to the pertinent open thread.

Not a worry - safe travels.

**Comment by jvican** [comment]
@dwijnand Tests continue to fail. Can you take care of this and I'll take care of #429? It'll be easier for you since the other longer PR has more sensitive commits that are context dependent. Will be no fun to rebase it, but someone has to do it, and I prefer to remove that hassle from you.

**Comment by jvican** [comment]
@dwijnand Let's close this, given that either of us have the time to work on this. Please re-open if you wanna tackle it soon.

**Pull request closed without merging**
