### PR TITLE
Support scala 2.13.0-pre-* & 2.13.0-M1

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes sbt/sbt#3771
Fixes sbt/zinc#460

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?zinc=pull/461/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Review by eed3si9n — APPROVED** [review]
LGTM

/cc @xuwei-k

**Comment by dwijnand** [comment]
Review by @sbt/scala-center-zinc-team?

**Review by jvican — APPROVED** [review]
LGTM!

**Pull request merged**
