### PR TITLE
Reduce overhead of workaround for Scala 2.11 on JDK9+

### PR DESCRIPTION
**Pull request by retronym**
Calling isDirectory on every reference is pretty excessive!

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/760/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/2031/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-pull/760/head-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/2031/">has checked</A> the following projects, tested using sources.sh.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@56cf50ff2385eb8468e2724d4d0e3a9262adc335
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/760">pull/760/head       </A> | sbt/zinc@b3f4cf54ef6c4fd4d5b4f7ee95e88dd296fed744
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@cd82d02d882e5d1eed7f90080a43095721310465
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@3b3aa2f495f579446ebae017fb70ca9d76eb9512
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@098796cdff7305a4aaadea9fdbba7fb6c23ff3ed

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=pull/760/head&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by eed3si9n — APPROVED** [review]

**Comment by retronym** [comment]
```
[info] Passed: Total 17, Failed 0, Errors 0, Passed 17
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:io_2.13:1.4.0-bin-20200424T012810
[error]   Not found
[error]   Not found
[error]   not found: /localhome/jenkinssbt/workspace/sbt-validator/.ivy/local/org.scala-sbt/io_2.13/1.4.0-bin-20200424T012810/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scala-sbt/io_2.13/1.4.0-bin-20200424T012810/io_2.13-1.4.0-bin-20200424T012810.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/io_2.13/1.4.0-bin-20200424T012810/io_2.13-1.4.0-bin-20200424T012810.pom
[error]   not found: https://dl.bintray.com/sbt/maven-releases/org/scala-sbt/io_2.13/1.4.0-bin-20200424T012810/io_2.13-1.4.0-bin-20200424T012810.pom
[error]   not found: https://dl.bintray.com/sbt/ivy-snapshots/org.scala-sbt/io_2.13/1.4.0-bin-20200424T012810/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io_2.13/1.4.0-bin-20200424T012810/ivys/ivy.xml
```

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/2032/console">is in progress...</a>

**Comment by retronym** [comment]
Trying a rerun.

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-pull/760/head-develop-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/2032/">has checked</A> the following projects, tested using sources.sh.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@56cf50ff2385eb8468e2724d4d0e3a9262adc335
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/760">pull/760/head       </A> | sbt/zinc@b3f4cf54ef6c4fd4d5b4f7ee95e88dd296fed744
  io                | <A HREF="https://github.com/sbt/io/tree/develop">develop             </A> | sbt/io@cd82d02d882e5d1eed7f90080a43095721310465
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@3b3aa2f495f579446ebae017fb70ca9d76eb9512
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@098796cdff7305a4aaadea9fdbba7fb6c23ff3ed

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=pull/760/head&io=develop&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by eed3si9n** [comment]
Sorry the nightly validation is currently broken, so you can ignore it for now.
The source is https://github.com/sbt/sbt-validator/blob/master/sources.sh, and it likely needs some maintenance to catch up with recent Zinc cross building. Also sbt/sbt needs to catch up to Zinc as well.

**Comment by retronym** [comment]
Thanks for the explanation, @eed3si9n.

**Pull request merged**
