### PR TITLE
Drop util-testing in favour of existing UnitSpec

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/328/head&deploy_to_bintray=false">this link.</A>

**Comment by dwijnand** [comment]
No idea what's happened to Drone. Let's give it the old close-and-reopen treatment.

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/328/head&deploy_to_bintray=false">this link.</A>

**Comment by dwijnand** [comment]
Looks like Drone won't trigger on this.. Great.

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/328/head&deploy_to_bintray=false">this link.</A>

**Comment by dwijnand** [comment]
Note to self: failing because the addition of zincTesting to zincClassfile doesn't work because:

+ zincTesting depends on lm
+ zincClassfile cross-builds to Scala 2.10
+ there is lm doesn't cross-build to Scala 2.10

**Comment by dwijnand** [comment]
Ignoring AppVeyor, this is actually green.

**Review by jvican — APPROVED** [review]
LGTM. Merging!

**Comment by jvican** [comment]
Oops, no, @Duhemm has to review this one yet.

**Comment by dwijnand** [comment]
@eed3si9n or @Duhemm, thoughts? I'm trying to diminish the dependencies between zinc and util, and this is a 1-line 1-class jar that I think we should drop.

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
