### PR TITLE
Scalafmt 1.3, sbt-scalafmt 1.14

### PR DESCRIPTION
**Pull request by dwijnand**
and merge 1.0.x into 1.x.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?zinc=pull/443/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by jvican** [comment]
Can you remove https://github.com/sbt/zinc/pull/443/commits/bb7112cdbe7b8cb32ffe3c399f801298e4bd678a? I think that's conflicting with my changes to the build, and I would prefer if I don't have to rebase it, we can incorporate it later.
  
The merge of 1.0.x to 1.x looks good.

**Comment by eed3si9n** [comment]
@dwijnand It seems that the Scalafmt thing is blocking the other useful "and merge 1.0.x into 1.x.", could we split this into two PRs, plz?

**Comment by dwijnand** [comment]
Merge 1.0.x into 1.x PR: https://github.com/sbt/zinc/pull/455

I'll rebase this PR once that's merged.

**Pull request closed without merging**
