### PR TITLE
Add failing test case for package object

### PR DESCRIPTION
**Pull request by allanrenucci**
This PR is meant to showcase an issue with incremental compilation for package object

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.x&zinc=pull/530/head&io=1.x&librarymanagement=1.x&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by allanrenucci** [comment]
Maybe [packageobject-and-traits](https://github.com/sbt/zinc/blob/1.x/zinc/src/sbt-test/source-dependencies/packageobject-and-traits/pending) already exercises the same issue

**Comment by dwijnand** [comment]
indeed, looks like it to me (but I'm a zinc amateur)

/cc @romanowski who submitted it in #289

**Review by eed3si9n — APPROVED** [review]
I like the fact that trait is not involved in this one. Until we find the exact mechanics of the bug my vote is to merge this as is.

**Comment by dwijnand** [comment]
sgtm, :+1:

**Review by jvican — APPROVED** [review]

**Pull request merged**
