### PR TITLE
Add callback allowing to switch to single files compilation mode

### PR DESCRIPTION
**Pull request by pkukielka**
For certain reasons this time I have to paste the below disclaimer:
THIS PROGRAM IS SUBJECT TO THE TERMS OF THE BSD 3-CLAUSE LICENSE.

THE FOLLOWING DISCLAIMER APPLIES TO ALL SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE:
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR
ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.
ONLY THE SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE, IF ANY, THAT ARE ATTACHED TO (OR OTHERWISE ACCOMPANY) THIS SUBMISSION (AND ORDINARY
COURSE CONTRIBUTIONS OF FUTURES PATCHES THERETO) ARE TO BE CONSIDERED A CONTRIBUTION. NO OTHER SOFTWARE CODE OR MATERIALS ARE A CONTRIBUTION.

### CODE REVIEW

**Comment by romanowski** [comment]
LGTM

**Comment by Duhemm** [comment]
Am I right that the goal is to bypass incremental recompilation entirely and recompile only the files that were modified? How is this different from [AntStyle incremental compilation](https://github.com/sbt/zinc/blob/1.0/internal/zinc-core/src/main/scala/sbt/internal/inc/IncrementalAntStyle.scala)?

**Comment by pkukielka** [comment]
@Duhemm 
You are right about the goal, but we cannot use AntStyle builder. 
This pull request (as several others before and after it) is aiming to bring zinc to IntelliJ (you will be able to choose zinc as default compiler). So we need normal incremental compilation (including name hashing) which only sometimes need to be switched to single files compilation (namely when someone uses 'Compile'). Moreover if after compiling single file user will hit 'Make', zinc should have correct analysis in place and continue compilation from there.

**Comment by romanowski** [comment]
Of course Intellij needs to handle all files that should be recompiled due to possible changes in compiled source (that is why `incrementallyInvalided` is passed to hook.

**Comment by Duhemm** [comment]
@pkukielka I see, thanks for the explanations. The only thing that worries me is that the incremental compiler is starting to have 2 different ways of being configured: `IncOptions` and `ExternalHooks`. Any reason not to put this setting in particular in `IncOptions`?

**Comment by romanowski** [comment]
External hooks are part of IncOptions - however this is Java code (with possible nulls) so that is why it is also accessible by Lookup instance.

https://github.com/sbt/zinc/blob/1.0/internal/compiler-interface/src/main/datatype/incremental.json#L145-L149
https://github.com/sbt/zinc/blob/1.0/internal/compiler-interface/src/main/java/xsbti/compile/IncOptionsUtil.java#L87-L99

**Comment by eed3si9n** [comment]
LGTM

**Pull request merged**
